### ISSUE TITLE
Error when ending full game all rounds

### ISSUE THREAD

**Issue by arimwilson** [evilrobot69/Joydom#2]
Unhandled error TypeError: Cannot read property 'length' of undefined
    at takeAction (/workspace/index.js:367:32)
    at /workspace/index.js:465:26
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async func (/workspace/node_modules/firebase-functions/lib/providers/https.js:336:26)

**Comment by arimwilson** [comment]
Fixed in https://github.com/evilrobot69/Joydom/commit/8f35e3d82d69c3cebbbbcf02151c095ed7df2659
